//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.13 at 05:19:41 PM IST 
//


package com.edms.folder;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edms.folder package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.edms.folder
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSharedFoldersByPathResponse }
     * 
     */
    public GetSharedFoldersByPathResponse createGetSharedFoldersByPathResponse() {
        return new GetSharedFoldersByPathResponse();
    }

    /**
     * Create an instance of {@link FolderListReturn }
     * 
     */
    public FolderListReturn createFolderListReturn() {
        return new FolderListReturn();
    }

    /**
     * Create an instance of {@link AssignSinglePermissionResponse }
     * 
     */
    public AssignSinglePermissionResponse createAssignSinglePermissionResponse() {
        return new AssignSinglePermissionResponse();
    }

    /**
     * Create an instance of {@link RestoreFolderRequest }
     * 
     */
    public RestoreFolderRequest createRestoreFolderRequest() {
        return new RestoreFolderRequest();
    }

    /**
     * Create an instance of {@link HasChildResponse }
     * 
     */
    public HasChildResponse createHasChildResponse() {
        return new HasChildResponse();
    }

    /**
     * Create an instance of {@link GetFolderByPathResponse }
     * 
     */
    public GetFolderByPathResponse createGetFolderByPathResponse() {
        return new GetFolderByPathResponse();
    }

    /**
     * Create an instance of {@link Folder }
     * 
     */
    public Folder createFolder() {
        return new Folder();
    }

    /**
     * Create an instance of {@link CreateFolderResponse }
     * 
     */
    public CreateFolderResponse createCreateFolderResponse() {
        return new CreateFolderResponse();
    }

    /**
     * Create an instance of {@link ShareFolderByPathRequest }
     * 
     */
    public ShareFolderByPathRequest createShareFolderByPathRequest() {
        return new ShareFolderByPathRequest();
    }

    /**
     * Create an instance of {@link HasChildRequest }
     * 
     */
    public HasChildRequest createHasChildRequest() {
        return new HasChildRequest();
    }

    /**
     * Create an instance of {@link RestoreVersionResponse }
     * 
     */
    public RestoreVersionResponse createRestoreVersionResponse() {
        return new RestoreVersionResponse();
    }

    /**
     * Create an instance of {@link CreateFolderRequest }
     * 
     */
    public CreateFolderRequest createCreateFolderRequest() {
        return new CreateFolderRequest();
    }

    /**
     * Create an instance of {@link RecycleFolderResponse }
     * 
     */
    public RecycleFolderResponse createRecycleFolderResponse() {
        return new RecycleFolderResponse();
    }

    /**
     * Create an instance of {@link GetRecycledDocsResponse }
     * 
     */
    public GetRecycledDocsResponse createGetRecycledDocsResponse() {
        return new GetRecycledDocsResponse();
    }

    /**
     * Create an instance of {@link ShareFolderByPathResponse }
     * 
     */
    public ShareFolderByPathResponse createShareFolderByPathResponse() {
        return new ShareFolderByPathResponse();
    }

    /**
     * Create an instance of {@link AssignSinglePermissionRequest }
     * 
     */
    public AssignSinglePermissionRequest createAssignSinglePermissionRequest() {
        return new AssignSinglePermissionRequest();
    }

    /**
     * Create an instance of {@link RestoreFolderResponse }
     * 
     */
    public RestoreFolderResponse createRestoreFolderResponse() {
        return new RestoreFolderResponse();
    }

    /**
     * Create an instance of {@link DeleteFolderResponse }
     * 
     */
    public DeleteFolderResponse createDeleteFolderResponse() {
        return new DeleteFolderResponse();
    }

    /**
     * Create an instance of {@link GetFolderResponse }
     * 
     */
    public GetFolderResponse createGetFolderResponse() {
        return new GetFolderResponse();
    }

    /**
     * Create an instance of {@link RestoreVersionRequest }
     * 
     */
    public RestoreVersionRequest createRestoreVersionRequest() {
        return new RestoreVersionRequest();
    }

    /**
     * Create an instance of {@link GetSharedFoldersByPathRequest }
     * 
     */
    public GetSharedFoldersByPathRequest createGetSharedFoldersByPathRequest() {
        return new GetSharedFoldersByPathRequest();
    }

    /**
     * Create an instance of {@link GetSharedFoldersRequest }
     * 
     */
    public GetSharedFoldersRequest createGetSharedFoldersRequest() {
        return new GetSharedFoldersRequest();
    }

    /**
     * Create an instance of {@link RenameFolderRequest }
     * 
     */
    public RenameFolderRequest createRenameFolderRequest() {
        return new RenameFolderRequest();
    }

    /**
     * Create an instance of {@link GetRecycledDocsRequest }
     * 
     */
    public GetRecycledDocsRequest createGetRecycledDocsRequest() {
        return new GetRecycledDocsRequest();
    }

    /**
     * Create an instance of {@link DeleteFolderRequest }
     * 
     */
    public DeleteFolderRequest createDeleteFolderRequest() {
        return new DeleteFolderRequest();
    }

    /**
     * Create an instance of {@link GetFolderRequest }
     * 
     */
    public GetFolderRequest createGetFolderRequest() {
        return new GetFolderRequest();
    }

    /**
     * Create an instance of {@link GetFolderByPathRequest }
     * 
     */
    public GetFolderByPathRequest createGetFolderByPathRequest() {
        return new GetFolderByPathRequest();
    }

    /**
     * Create an instance of {@link RecycleFolderRequest }
     * 
     */
    public RecycleFolderRequest createRecycleFolderRequest() {
        return new RecycleFolderRequest();
    }

    /**
     * Create an instance of {@link GetSharedFoldersResponse }
     * 
     */
    public GetSharedFoldersResponse createGetSharedFoldersResponse() {
        return new GetSharedFoldersResponse();
    }

    /**
     * Create an instance of {@link RenameFolderResponse }
     * 
     */
    public RenameFolderResponse createRenameFolderResponse() {
        return new RenameFolderResponse();
    }

    /**
     * Create an instance of {@link RenameFolderRes }
     * 
     */
    public RenameFolderRes createRenameFolderRes() {
        return new RenameFolderRes();
    }

    /**
     * Create an instance of {@link ArrayOfFolders }
     * 
     */
    public ArrayOfFolders createArrayOfFolders() {
        return new ArrayOfFolders();
    }

    /**
     * Create an instance of {@link FolderVersionDetail }
     * 
     */
    public FolderVersionDetail createFolderVersionDetail() {
        return new FolderVersionDetail();
    }

}
