//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.19 at 10:40:46 AM IST 
//


package com.edms.folder;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recentlyModifiedFiles" type="{http://edms.com/Folder}FolderListReturn"/>
 *         &lt;element name="recentlyModifiedFolders" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recentlyModifiedFiles",
    "recentlyModifiedFolders"
})
@XmlRootElement(name = "recentlyModifiedResponse")
public class RecentlyModifiedResponse {

    @XmlElement(required = true)
    protected FolderListReturn recentlyModifiedFiles;
    protected boolean recentlyModifiedFolders;

    /**
     * Gets the value of the recentlyModifiedFiles property.
     * 
     * @return
     *     possible object is
     *     {@link FolderListReturn }
     *     
     */
    public FolderListReturn getRecentlyModifiedFiles() {
        return recentlyModifiedFiles;
    }

    /**
     * Sets the value of the recentlyModifiedFiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link FolderListReturn }
     *     
     */
    public void setRecentlyModifiedFiles(FolderListReturn value) {
        this.recentlyModifiedFiles = value;
    }

    /**
     * Gets the value of the recentlyModifiedFolders property.
     * 
     */
    public boolean isRecentlyModifiedFolders() {
        return recentlyModifiedFolders;
    }

    /**
     * Sets the value of the recentlyModifiedFolders property.
     * 
     */
    public void setRecentlyModifiedFolders(boolean value) {
        this.recentlyModifiedFolders = value;
    }

}
