//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.18 at 06:06:05 PM IST 
//


package com.edms.documentmodule;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edms.documentmodule package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.edms.documentmodule
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSharedFoldersByPathResponse }
     * 
     */
    public GetSharedFoldersByPathResponse createGetSharedFoldersByPathResponse() {
        return new GetSharedFoldersByPathResponse();
    }

    /**
     * Create an instance of {@link FolderListReturn }
     * 
     */
    public FolderListReturn createFolderListReturn() {
        return new FolderListReturn();
    }

    /**
     * Create an instance of {@link SearchDocByDateResponse }
     * 
     */
    public SearchDocByDateResponse createSearchDocByDateResponse() {
        return new SearchDocByDateResponse();
    }

    /**
     * Create an instance of {@link FilesAndFolders }
     * 
     */
    public FilesAndFolders createFilesAndFolders() {
        return new FilesAndFolders();
    }

    /**
     * Create an instance of {@link CreateFileRequest }
     * 
     */
    public CreateFileRequest createCreateFileRequest() {
        return new CreateFileRequest();
    }

    /**
     * Create an instance of {@link RestoreFolderRequest }
     * 
     */
    public RestoreFolderRequest createRestoreFolderRequest() {
        return new RestoreFolderRequest();
    }

    /**
     * Create an instance of {@link EditFileResponse }
     * 
     */
    public EditFileResponse createEditFileResponse() {
        return new EditFileResponse();
    }

    /**
     * Create an instance of {@link EditFileRes }
     * 
     */
    public EditFileRes createEditFileRes() {
        return new EditFileRes();
    }

    /**
     * Create an instance of {@link GetFileByPathResponse }
     * 
     */
    public GetFileByPathResponse createGetFileByPathResponse() {
        return new GetFileByPathResponse();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link CreateFileResponse }
     * 
     */
    public CreateFileResponse createCreateFileResponse() {
        return new CreateFileResponse();
    }

    /**
     * Create an instance of {@link GetVCFFileRequest }
     * 
     */
    public GetVCFFileRequest createGetVCFFileRequest() {
        return new GetVCFFileRequest();
    }

    /**
     * Create an instance of {@link AddKeywordResponse }
     * 
     */
    public AddKeywordResponse createAddKeywordResponse() {
        return new AddKeywordResponse();
    }

    /**
     * Create an instance of {@link RecycleFileRequest }
     * 
     */
    public RecycleFileRequest createRecycleFileRequest() {
        return new RecycleFileRequest();
    }

    /**
     * Create an instance of {@link GetFolderByPathResponse }
     * 
     */
    public GetFolderByPathResponse createGetFolderByPathResponse() {
        return new GetFolderByPathResponse();
    }

    /**
     * Create an instance of {@link Folder }
     * 
     */
    public Folder createFolder() {
        return new Folder();
    }

    /**
     * Create an instance of {@link HasChildResponse }
     * 
     */
    public HasChildResponse createHasChildResponse() {
        return new HasChildResponse();
    }

    /**
     * Create an instance of {@link ShareFileByPathRequest }
     * 
     */
    public ShareFileByPathRequest createShareFileByPathRequest() {
        return new ShareFileByPathRequest();
    }

    /**
     * Create an instance of {@link CreateFolderResponse }
     * 
     */
    public CreateFolderResponse createCreateFolderResponse() {
        return new CreateFolderResponse();
    }

    /**
     * Create an instance of {@link EditFileRequest }
     * 
     */
    public EditFileRequest createEditFileRequest() {
        return new EditFileRequest();
    }

    /**
     * Create an instance of {@link SearchDocByDateRequest }
     * 
     */
    public SearchDocByDateRequest createSearchDocByDateRequest() {
        return new SearchDocByDateRequest();
    }

    /**
     * Create an instance of {@link RecentlyModifiedRequest }
     * 
     */
    public RecentlyModifiedRequest createRecentlyModifiedRequest() {
        return new RecentlyModifiedRequest();
    }

    /**
     * Create an instance of {@link SearchDocByLikeRequest }
     * 
     */
    public SearchDocByLikeRequest createSearchDocByLikeRequest() {
        return new SearchDocByLikeRequest();
    }

    /**
     * Create an instance of {@link RestoreFileResponse }
     * 
     */
    public RestoreFileResponse createRestoreFileResponse() {
        return new RestoreFileResponse();
    }

    /**
     * Create an instance of {@link ShareFolderByPathRequest }
     * 
     */
    public ShareFolderByPathRequest createShareFolderByPathRequest() {
        return new ShareFolderByPathRequest();
    }

    /**
     * Create an instance of {@link HasChildRequest }
     * 
     */
    public HasChildRequest createHasChildRequest() {
        return new HasChildRequest();
    }

    /**
     * Create an instance of {@link RestoreVersionResponse }
     * 
     */
    public RestoreVersionResponse createRestoreVersionResponse() {
        return new RestoreVersionResponse();
    }

    /**
     * Create an instance of {@link GetSharedFilesResponse }
     * 
     */
    public GetSharedFilesResponse createGetSharedFilesResponse() {
        return new GetSharedFilesResponse();
    }

    /**
     * Create an instance of {@link FileListReturn }
     * 
     */
    public FileListReturn createFileListReturn() {
        return new FileListReturn();
    }

    /**
     * Create an instance of {@link SortByPropertyRequest }
     * 
     */
    public SortByPropertyRequest createSortByPropertyRequest() {
        return new SortByPropertyRequest();
    }

    /**
     * Create an instance of {@link SortByPropertyResponse }
     * 
     */
    public SortByPropertyResponse createSortByPropertyResponse() {
        return new SortByPropertyResponse();
    }

    /**
     * Create an instance of {@link SortByPropertyRes }
     * 
     */
    public SortByPropertyRes createSortByPropertyRes() {
        return new SortByPropertyRes();
    }

    /**
     * Create an instance of {@link ShareFolderByPathResponse }
     * 
     */
    public ShareFolderByPathResponse createShareFolderByPathResponse() {
        return new ShareFolderByPathResponse();
    }

    /**
     * Create an instance of {@link ShareFileByPathResponse }
     * 
     */
    public ShareFileByPathResponse createShareFileByPathResponse() {
        return new ShareFileByPathResponse();
    }

    /**
     * Create an instance of {@link AssignSinglePermissionRequest }
     * 
     */
    public AssignSinglePermissionRequest createAssignSinglePermissionRequest() {
        return new AssignSinglePermissionRequest();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathRequest }
     * 
     */
    public GetSharedFilesByPathRequest createGetSharedFilesByPathRequest() {
        return new GetSharedFilesByPathRequest();
    }

    /**
     * Create an instance of {@link RestoreVersionRequest }
     * 
     */
    public RestoreVersionRequest createRestoreVersionRequest() {
        return new RestoreVersionRequest();
    }

    /**
     * Create an instance of {@link GetFileByPathRequest }
     * 
     */
    public GetFileByPathRequest createGetFileByPathRequest() {
        return new GetFileByPathRequest();
    }

    /**
     * Create an instance of {@link GetSharedFoldersRequest }
     * 
     */
    public GetSharedFoldersRequest createGetSharedFoldersRequest() {
        return new GetSharedFoldersRequest();
    }

    /**
     * Create an instance of {@link RenameFolderRequest }
     * 
     */
    public RenameFolderRequest createRenameFolderRequest() {
        return new RenameFolderRequest();
    }

    /**
     * Create an instance of {@link AddKeywordRequest }
     * 
     */
    public AddKeywordRequest createAddKeywordRequest() {
        return new AddKeywordRequest();
    }

    /**
     * Create an instance of {@link DeleteFolderRequest }
     * 
     */
    public DeleteFolderRequest createDeleteFolderRequest() {
        return new DeleteFolderRequest();
    }

    /**
     * Create an instance of {@link GetFolderByPathRequest }
     * 
     */
    public GetFolderByPathRequest createGetFolderByPathRequest() {
        return new GetFolderByPathRequest();
    }

    /**
     * Create an instance of {@link RecycleFolderRequest }
     * 
     */
    public RecycleFolderRequest createRecycleFolderRequest() {
        return new RecycleFolderRequest();
    }

    /**
     * Create an instance of {@link GetSharedFoldersResponse }
     * 
     */
    public GetSharedFoldersResponse createGetSharedFoldersResponse() {
        return new GetSharedFoldersResponse();
    }

    /**
     * Create an instance of {@link AssignSinglePermissionResponse }
     * 
     */
    public AssignSinglePermissionResponse createAssignSinglePermissionResponse() {
        return new AssignSinglePermissionResponse();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathResponse }
     * 
     */
    public GetSharedFilesByPathResponse createGetSharedFilesByPathResponse() {
        return new GetSharedFilesByPathResponse();
    }

    /**
     * Create an instance of {@link DeleteFileResponse }
     * 
     */
    public DeleteFileResponse createDeleteFileResponse() {
        return new DeleteFileResponse();
    }

    /**
     * Create an instance of {@link RenameFileResponse }
     * 
     */
    public RenameFileResponse createRenameFileResponse() {
        return new RenameFileResponse();
    }

    /**
     * Create an instance of {@link RenameFileRes }
     * 
     */
    public RenameFileRes createRenameFileRes() {
        return new RenameFileRes();
    }

    /**
     * Create an instance of {@link RecycleFileResponse }
     * 
     */
    public RecycleFileResponse createRecycleFileResponse() {
        return new RecycleFileResponse();
    }

    /**
     * Create an instance of {@link RecentlyModifiedResponse }
     * 
     */
    public RecentlyModifiedResponse createRecentlyModifiedResponse() {
        return new RecentlyModifiedResponse();
    }

    /**
     * Create an instance of {@link GetFileRequest }
     * 
     */
    public GetFileRequest createGetFileRequest() {
        return new GetFileRequest();
    }

    /**
     * Create an instance of {@link RenameFileRequest }
     * 
     */
    public RenameFileRequest createRenameFileRequest() {
        return new RenameFileRequest();
    }

    /**
     * Create an instance of {@link RecycleFolderResponse }
     * 
     */
    public RecycleFolderResponse createRecycleFolderResponse() {
        return new RecycleFolderResponse();
    }

    /**
     * Create an instance of {@link CreateFolderRequest }
     * 
     */
    public CreateFolderRequest createCreateFolderRequest() {
        return new CreateFolderRequest();
    }

    /**
     * Create an instance of {@link GetRecycledDocsResponse }
     * 
     */
    public GetRecycledDocsResponse createGetRecycledDocsResponse() {
        return new GetRecycledDocsResponse();
    }

    /**
     * Create an instance of {@link GetSharedFilesRequest }
     * 
     */
    public GetSharedFilesRequest createGetSharedFilesRequest() {
        return new GetSharedFilesRequest();
    }

    /**
     * Create an instance of {@link GetVCFFileResponse }
     * 
     */
    public GetVCFFileResponse createGetVCFFileResponse() {
        return new GetVCFFileResponse();
    }

    /**
     * Create an instance of {@link VCFFileListReturn }
     * 
     */
    public VCFFileListReturn createVCFFileListReturn() {
        return new VCFFileListReturn();
    }

    /**
     * Create an instance of {@link RestoreFolderResponse }
     * 
     */
    public RestoreFolderResponse createRestoreFolderResponse() {
        return new RestoreFolderResponse();
    }

    /**
     * Create an instance of {@link DeleteFolderResponse }
     * 
     */
    public DeleteFolderResponse createDeleteFolderResponse() {
        return new DeleteFolderResponse();
    }

    /**
     * Create an instance of {@link GetFolderResponse }
     * 
     */
    public GetFolderResponse createGetFolderResponse() {
        return new GetFolderResponse();
    }

    /**
     * Create an instance of {@link GetSharedFoldersByPathRequest }
     * 
     */
    public GetSharedFoldersByPathRequest createGetSharedFoldersByPathRequest() {
        return new GetSharedFoldersByPathRequest();
    }

    /**
     * Create an instance of {@link RestoreFileRequest }
     * 
     */
    public RestoreFileRequest createRestoreFileRequest() {
        return new RestoreFileRequest();
    }

    /**
     * Create an instance of {@link DeleteFileRequest }
     * 
     */
    public DeleteFileRequest createDeleteFileRequest() {
        return new DeleteFileRequest();
    }

    /**
     * Create an instance of {@link RemoveKeywordRequest }
     * 
     */
    public RemoveKeywordRequest createRemoveKeywordRequest() {
        return new RemoveKeywordRequest();
    }

    /**
     * Create an instance of {@link SearchDocByLikeResponse }
     * 
     */
    public SearchDocByLikeResponse createSearchDocByLikeResponse() {
        return new SearchDocByLikeResponse();
    }

    /**
     * Create an instance of {@link GetFileResponse }
     * 
     */
    public GetFileResponse createGetFileResponse() {
        return new GetFileResponse();
    }

    /**
     * Create an instance of {@link RemoveKeywordResponse }
     * 
     */
    public RemoveKeywordResponse createRemoveKeywordResponse() {
        return new RemoveKeywordResponse();
    }

    /**
     * Create an instance of {@link GetRecycledDocsRequest }
     * 
     */
    public GetRecycledDocsRequest createGetRecycledDocsRequest() {
        return new GetRecycledDocsRequest();
    }

    /**
     * Create an instance of {@link GetFolderRequest }
     * 
     */
    public GetFolderRequest createGetFolderRequest() {
        return new GetFolderRequest();
    }

    /**
     * Create an instance of {@link RenameFolderResponse }
     * 
     */
    public RenameFolderResponse createRenameFolderResponse() {
        return new RenameFolderResponse();
    }

    /**
     * Create an instance of {@link RenameFolderRes }
     * 
     */
    public RenameFolderRes createRenameFolderRes() {
        return new RenameFolderRes();
    }

    /**
     * Create an instance of {@link ArrayOfFolders }
     * 
     */
    public ArrayOfFolders createArrayOfFolders() {
        return new ArrayOfFolders();
    }

    /**
     * Create an instance of {@link ArrayOfFiles }
     * 
     */
    public ArrayOfFiles createArrayOfFiles() {
        return new ArrayOfFiles();
    }

    /**
     * Create an instance of {@link VCFFileAtt }
     * 
     */
    public VCFFileAtt createVCFFileAtt() {
        return new VCFFileAtt();
    }

    /**
     * Create an instance of {@link FileVersionDetail }
     * 
     */
    public FileVersionDetail createFileVersionDetail() {
        return new FileVersionDetail();
    }

    /**
     * Create an instance of {@link ArrayOfVCFFiles }
     * 
     */
    public ArrayOfVCFFiles createArrayOfVCFFiles() {
        return new ArrayOfVCFFiles();
    }

    /**
     * Create an instance of {@link FolderVersionDetail }
     * 
     */
    public FolderVersionDetail createFolderVersionDetail() {
        return new FolderVersionDetail();
    }

}
