//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.13 at 05:19:41 PM IST 
//


package com.edms.file;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edms.file package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.edms.file
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathResponse }
     * 
     */
    public GetSharedFilesByPathResponse createGetSharedFilesByPathResponse() {
        return new GetSharedFilesByPathResponse();
    }

    /**
     * Create an instance of {@link FileListReturn }
     * 
     */
    public FileListReturn createFileListReturn() {
        return new FileListReturn();
    }

    /**
     * Create an instance of {@link CreateFileRequest }
     * 
     */
    public CreateFileRequest createCreateFileRequest() {
        return new CreateFileRequest();
    }

    /**
     * Create an instance of {@link GetSharedFilesRequest }
     * 
     */
    public GetSharedFilesRequest createGetSharedFilesRequest() {
        return new GetSharedFilesRequest();
    }

    /**
     * Create an instance of {@link GetFileByPathResponse }
     * 
     */
    public GetFileByPathResponse createGetFileByPathResponse() {
        return new GetFileByPathResponse();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link ShareFileByPathResponse }
     * 
     */
    public ShareFileByPathResponse createShareFileByPathResponse() {
        return new ShareFileByPathResponse();
    }

    /**
     * Create an instance of {@link CreateFileResponse }
     * 
     */
    public CreateFileResponse createCreateFileResponse() {
        return new CreateFileResponse();
    }

    /**
     * Create an instance of {@link GetSharedFilesByPathRequest }
     * 
     */
    public GetSharedFilesByPathRequest createGetSharedFilesByPathRequest() {
        return new GetSharedFilesByPathRequest();
    }

    /**
     * Create an instance of {@link RecycleFileRequest }
     * 
     */
    public RecycleFileRequest createRecycleFileRequest() {
        return new RecycleFileRequest();
    }

    /**
     * Create an instance of {@link ShareFileByPathRequest }
     * 
     */
    public ShareFileByPathRequest createShareFileByPathRequest() {
        return new ShareFileByPathRequest();
    }

    /**
     * Create an instance of {@link GetFileByPathRequest }
     * 
     */
    public GetFileByPathRequest createGetFileByPathRequest() {
        return new GetFileByPathRequest();
    }

    /**
     * Create an instance of {@link RestoreFileRequest }
     * 
     */
    public RestoreFileRequest createRestoreFileRequest() {
        return new RestoreFileRequest();
    }

    /**
     * Create an instance of {@link DeleteFileResponse }
     * 
     */
    public DeleteFileResponse createDeleteFileResponse() {
        return new DeleteFileResponse();
    }

    /**
     * Create an instance of {@link DeleteFileRequest }
     * 
     */
    public DeleteFileRequest createDeleteFileRequest() {
        return new DeleteFileRequest();
    }

    /**
     * Create an instance of {@link RenameFileResponse }
     * 
     */
    public RenameFileResponse createRenameFileResponse() {
        return new RenameFileResponse();
    }

    /**
     * Create an instance of {@link RenameFileRes }
     * 
     */
    public RenameFileRes createRenameFileRes() {
        return new RenameFileRes();
    }

    /**
     * Create an instance of {@link RecycleFileResponse }
     * 
     */
    public RecycleFileResponse createRecycleFileResponse() {
        return new RecycleFileResponse();
    }

    /**
     * Create an instance of {@link GetFileRequest }
     * 
     */
    public GetFileRequest createGetFileRequest() {
        return new GetFileRequest();
    }

    /**
     * Create an instance of {@link GetFileResponse }
     * 
     */
    public GetFileResponse createGetFileResponse() {
        return new GetFileResponse();
    }

    /**
     * Create an instance of {@link RestoreFileResponse }
     * 
     */
    public RestoreFileResponse createRestoreFileResponse() {
        return new RestoreFileResponse();
    }

    /**
     * Create an instance of {@link RenameFileRequest }
     * 
     */
    public RenameFileRequest createRenameFileRequest() {
        return new RenameFileRequest();
    }

    /**
     * Create an instance of {@link GetSharedFilesResponse }
     * 
     */
    public GetSharedFilesResponse createGetSharedFilesResponse() {
        return new GetSharedFilesResponse();
    }

    /**
     * Create an instance of {@link FileVersionDetail }
     * 
     */
    public FileVersionDetail createFileVersionDetail() {
        return new FileVersionDetail();
    }

    /**
     * Create an instance of {@link ArrayOfFiles }
     * 
     */
    public ArrayOfFiles createArrayOfFiles() {
        return new ArrayOfFiles();
    }

}
