//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.03 at 01:32:14 PM IST 
//


package com.edms.workflowhistory;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.edms.workflowhistory package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.edms.workflowhistory
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetHistoryTaskInstanceRequest }
     * 
     */
    public GetHistoryTaskInstanceRequest createGetHistoryTaskInstanceRequest() {
        return new GetHistoryTaskInstanceRequest();
    }

    /**
     * Create an instance of {@link GetProcessVariablesResponse }
     * 
     */
    public GetProcessVariablesResponse createGetProcessVariablesResponse() {
        return new GetProcessVariablesResponse();
    }

    /**
     * Create an instance of {@link HistDetVrblInstUpdateEntityReturn }
     * 
     */
    public HistDetVrblInstUpdateEntityReturn createHistDetVrblInstUpdateEntityReturn() {
        return new HistDetVrblInstUpdateEntityReturn();
    }

    /**
     * Create an instance of {@link GetProcessVariablesRequest }
     * 
     */
    public GetProcessVariablesRequest createGetProcessVariablesRequest() {
        return new GetProcessVariablesRequest();
    }

    /**
     * Create an instance of {@link GetHistoryTaskInstanceResponse }
     * 
     */
    public GetHistoryTaskInstanceResponse createGetHistoryTaskInstanceResponse() {
        return new GetHistoryTaskInstanceResponse();
    }

    /**
     * Create an instance of {@link HistTaskInstListReturn }
     * 
     */
    public HistTaskInstListReturn createHistTaskInstListReturn() {
        return new HistTaskInstListReturn();
    }

    /**
     * Create an instance of {@link HistTaskInstList }
     * 
     */
    public HistTaskInstList createHistTaskInstList() {
        return new HistTaskInstList();
    }

    /**
     * Create an instance of {@link HistDetVrblInstUpdateEntity }
     * 
     */
    public HistDetVrblInstUpdateEntity createHistDetVrblInstUpdateEntity() {
        return new HistDetVrblInstUpdateEntity();
    }

}
